---
- hosts: all
  sudo: yes

  tasks:
      - name: Install docker
        apt:
            name: docker.io
            state: latest
      - name: Install supervisor
        apt:
            name: supervisor
            state: latest
      - name: Copy files
        copy: src=config/nginx.conf dest=/etc/nginx/nginx.conf
        copy: src=src/index.php dest=/var/www/html/index.php
        copy: src=supervisord.conf dest=/etc/supervisor/conf.d/supervisord.conf

      - supervisorctl:
            name: docker
#            ignore_errors: yes
            state: present
            config: supervisord.conf

#      - supervisorctl:
      - name: Supervisor
        command: systemctl enable supervisor
            

  environment:
      - PATH: /opt/run/webphp/{log,config}:{{ ansible_env.PATH }}

